# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Build Docker image and publish to pulp-platform's GHCR.
name: build-docker
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'util/container/Dockerfile'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kuleuven-micas/snax
jobs:
  build-docker:
    name: Deploy Docker image
    runs-on: ubuntu-22.04
    steps:
      # Free up disk space on Github-hosted runner
      - name: Disk usage
        run: df -h
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
      - name: Disk usage after freeing up space
        run: df -h
      # Actually build the Docker container
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - name: GHCR Log-in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: util/container/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
