# Copyright 2024 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: Template and Chisel Generation
on:
  push:
    branches: ["main"]
  pull_request:
jobs:

  #####################
  # Generation Checks #
  #####################
  gen_checks:
    name: Generation checks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kuleuven-micas/snax:main
    steps:
      - uses: actions/checkout@v2
      - name: Check wrapper, parameter, and chisel generation
        run: |
          ./util/wrappergen/wrappergen.py \
          --cfg_path="./target/snitch_cluster/cfg/snax-alu.hjson" \
          --tpl_path="./hw/templates/" \
          --chisel_path="./hw/chisel" \
          --gen_path="./target/snitch_cluster/generated/"
